### ISSUE TITLE
Tabs component using improper roles and ARIA

### ISSUE THREAD

**Issue by Firestorm980** [10up/component-tabs#1]
From https://github.com/10up/wp-component-library/issues/170

See discussion there as well.

---
**Original Issue**

The current tabs component has a few outstanding issues that are affecting its use with various screen readers (specifically "Narrator" in Windows 10). This issue is mainly for a note for our current refactor so that it can be resolved when working on that (hence the "won't fix"). There will also be an issue posted in that repo as well (just in case).

The component is missing the following role attributes:

- tablist
- tab
- tabpanel

Additionally, tab items are missing the following ARIA attributes:

- aria-controls
- aria-setsize
- aria-posinset

**Comment by kdo** [comment]
@timwright12 Opened PR #7 for this!
I think since all tabs are in the markup, there's no need for `aria-setsize` and `aria-posinset`.

Thanks!

**Comment by Firestorm980** [comment]
@kdo did we test if Windows Narrator was able to properly announce where you were in tabs? It isn't a very popular reader, but that is the main reason the properties were there (all other SR's seemed to work fine without them specified, if I remember right).

**Comment by kdo** [comment]
@Firestorm980 thanks for the warning! I'll test it this week :)

**Comment by kdo** [comment]
Hi @Firestorm980 I tested #7 on Windows 10 using Narrator, it seems to announce properly for me
Thanks!
