### ISSUE TITLE
IE11 does not support Object.assign();

### ISSUE THREAD

**Issue by dainemawer** [10up/component-tabs#15]
**Describe the bug**
Not sure if there should be a fallback for this in the component or in the theme-scaffold / project but - in IE11, `Object.assign` is not supported. Script execution is stopped, thus breaking any functionality found further on in the execution order.

**To Reproduce**
Steps to reproduce the behaviour:
1. Culprit: https://github.com/10up/component-tabs/blob/07a7403b9d7fb16cde2f2e97432a5cb7fa91cb96/src/tabs.js#L66
2. Implement Tabs, view in IE11
2. See Console Error: "Object doesn't support property or method 'assign'"

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Internet Explorer
 - Version: 11

**Comment by timwright12** [comment]
@dainemawer can you retest this? I wasn't able to replicate, I think maybe it just got fixed at some point

**Comment by timwright12** [comment]
I think we fixed this, closing out
