### ISSUE TITLE
readme updates

### ISSUE THREAD

**Issue by jeffpaul** [10up/component-tabs#17]
**Is your feature request related to a problem? Please describe.**
It's not obvious the level of support provided for this repo, so let's add some clarification.

**Describe the solution you'd like**
- [x] add support level section and badge
- [ ] add license file and badge

**Describe alternatives you've considered**
none.

**Comment by jeffpaul** [comment]
As there's no license described in the repo, I'm holding off on applying a license file and badge until the license is confirmed.

**Comment by timwright12** [comment]
@jeffpaul added MIT
