### ISSUE TITLE
Losing :focus when using links inside tabs

### ISSUE THREAD

**Issue by LehtinenRiku** [10up/component-tabs#25]
**Describe the bug**
If tabpanel(s) include links, :focus disappears or goes to inactive tab and is not trapped inside of the active tab when browsing with tab key.

**To Reproduce**
1. Add links to tabs of the demo index.html
```
<div class="tab-content" id="js-tab1" role="tabpanel">
  <h2>Tab 1 Content</h2>
  <p><a href="#1">Link-1</a> ipsum dolor sit amet, consectetur adipiscing elit.</p>
</div><!-- //.tab-content -->

<div class="tab-content" id="js-tab2" role="tabpanel">
  <h2>Tab 2 Content</h2>
  <p><a href="#2">Link-2</a> tincidunt tempor risus gravida tincidunt.</p>
</div><!-- //.tab-content -->
```
2. Open in browser
3. Browse with tab key
4. After focusing "Link-1" press tab again
5. Focus now goes to "Link-2" but it's not clear to user that tab has changed.

**Expected behavior**
User could tab-browse all links inside of a tab, and then focus moves to next .tab-item (where you change tab).

**Desktop (please complete the following information):**
 - OS: [Mac OS Catalina]
 - Browser [Atleast all webkit browsers]

**Mobile (please complete the following information):**
- Not an issue on mobile device, atleast when using touchscreen

**Comment by Firestorm980** [comment]
Looking at this particular issue, I can confirm that focus does indeed get lost. However, the suggested fix (tab moving to the next tab item) doesn't appear to follow the W3C guidelines.

According to the example that W3C has https://w3c.github.io/aria-practices/examples/tabs/tabs-1/tabs.html and an example at Inclusive Components https://inclusive-components.design/tabbed-interfaces/, inactive tabs should be `hidden` or `display: none`, making it so their links wouldn't be able to be tabbed to by the user. This would avoid the confusion as to lost focus, as well as maintaining proper focus order. A user would be required to go back to the tab item to get to the next one (via non-tab keys).

cc: @timwright12

**Comment by nicholasio** [comment]
Closing in favor of: https://github.com/10up/component-library/issues/18
