### ISSUE TITLE
Incorrect entry file in package.json

### ISSUE THREAD

**Issue by ivankruchkoff** [10up/component-tabs#27]
**Describe the bug**
Incorrect entry file in JS, links to src, but should use transpiled version in dist.
https://github.com/10up/component-tabs/blob/11aef98/package.json#L6

Causing this issue in downstream dependencies: 10up/theme-scaffold#183

**Comment by timwright12** [comment]
Hold off on this one

**Comment by nicholasio** [comment]
This has been addressed here: https://github.com/10up/component-library/pull/10
